### ISSUE TITLE
作者您好,能耽误您一下吗,在构建的时候遇到assert问题

### ISSUE THREAD

**Issue by huyunlei** [Syencil/ncnn-android-projects#1]
这个错误您知道吗? use of undeclared identifier 'assert'  在构建apk时候出现的3个assert错误
您方便给一个建议吗,目前c++还不是很熟练, 很想运行一下🙏

**Comment by Daisy-bit** [comment]
> 这个错误您知道吗? use of undeclared identifier 'assert' 在构建apk时候出现的3个assert错误
> 您方便给一个建议吗,目前c++还不是很熟练, 很想运行一下🙏

您好，请问你现在解决这个问题了吗

**Comment by huyunlei** [comment]
没有

**Comment by Syencil** [comment]
sdk版本问题 这个你找懂android的人问问就知道了

**Comment by Daisy-bit** [comment]
> sdk版本问题 这个你找懂android的人问问就知道了

已解决，感谢您的回复
